server:
   port: 9090

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 8
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
  instances:
    propsCB:
      baseConfig: default
      permittedNumberOfCallsInHalfOpenState: 24
      waitDurationInOpenState: 5000
    oldCB:
      baseConfig: default
      permittedNumberOfCallsInHalfOpenState: 11
# circuit-breaker-aspect-order: 2


resilience4j.ratelimiter:
  instances:
    propsRL:
      limitForPeriod: 1
      limitRefreshPeriod: 1s
      timeoutDuration: 1s
# rate-limiter-aspect-order: 1
